name: Style

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: make lint

      - name: StyLua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            # CLI arguments
            args: --check .
            version: v0.14.3
